### ISSUE TITLE
Crash when hovering over newly crafted shield

### ISSUE THREAD

**Issue by darkphan** [shiroroku/DMCLoot#1]
Crashlog: https://gist.github.com/darkphan/e44b5f9ffb3f88a0f8cf50d3c16df1ed

Version: dmcloot-1.16.5-beta-aug0321

**Comment by shiroroku** [comment]
did you modify the config file, and can you please post it if you did?
also does this happen for other common rarity items?

**Comment by darkphan** [comment]
It is just the default config. This was the only time we have had a crash so far.

**Comment by darkphan** [comment]
here is the data on the shield in my playerfile: [image](https://i.imgur.com/erZeXjX.png)

**Comment by shiroroku** [comment]
https://github.com/shiroroku/DMCLoot/commit/e8e3be2d1894ece4ec639330bf56cd48ba4d8fb0

hopefully this will fix it
